#!/bin/bash

# RUN EXPRESSO TO IDENTIFY TEMPLATES
mkdir OUTPUT
t_coffee -other_pg seq_reformat -in PF*.fasta -action +trim _seq_%%99_ > data_99.fasta
t_coffee data_99.fasta  -mode expresso -blast=LOCAL -pdb_db=/db/ncbi/201304/blast/db/pdbaa.fa -pdb_type d -pdb_min_sim 95 -pdb_min_cov 95 -cache $PWD
#t_coffee data_99.fasta  -mode expresso -blast=LOCAL -pdb_db=/db/pdb/derived_data_format/blast/latest/pdb_seqres.fa -pdb_type d -pdb_min_sim 95 -pdb_min_cov 95 -cache $PWD
mv *tmp *results *dnd *html plot.rms OUTPUT
grep _P_  *_pdb1.template_list > temp.list
t_coffee -other_pg seq_reformat -in data_99.fasta -action +extract_seq_list temp.list > temp.fasta

# MODIFY THE PDB FILES AND THE TEMPLATES AND CREATE FASTA (ONE PER ALIGNER) 
perl PDB_extract.pl
cp modified.fasta sap.fasta
cp modified.fasta mustang.fasta
cp modified.fasta tmalign.fasta
cp modified.fasta tcoffee.fasta
cp modified.fasta psicoffee.fasta
cp modified.fasta mcoffee.fasta
cp modified.fasta 3Dmcoffee.fasta
cp modified.fasta sap_proba.fasta
cp modified.fasta mustang_proba.fasta
cp modified.fasta tmalign_proba.fasta
cp modified.fasta sap_mustang.fasta
cp modified.fasta mustang_tmalign.fasta
cp modified.fasta tmalign_sap.fasta
cp modified.fasta clustalw.fasta
cp modified.fasta mafft.fasta
cp modified.fasta msaprobs.fasta
cp modified.fasta muscle.fasta
cp modified.fasta prank.fasta
cp modified.fasta probcons.fasta
cp modified.fasta sate.fasta

# ALIGNMENT TIME !!!!!

# The ones that generate the library need the PDB structures
t_coffee sap.fasta -template_file modified.template -method sap_pair -out_lib sap.lib
t_coffee mustang.fasta -template_file modified.template -method mustang_pair -out_lib mustang.lib
t_coffee tmalign.fasta -template_file modified.template -method TMalign_pair -out_lib tmalign.lib
t_coffee tcoffee.fasta -out_lib tcoffee.lib
t_coffee mcoffee.fasta -mode mcoffee -out_lib mcoffee.lib

# This doesn't need the PDBs
t_coffee 3Dmcoffee.fasta -lib sap.lib mustang.lib tmalign.lib
t_coffee sap_proba.fasta -lib tcoffee.lib sap.lib
t_coffee mustang_proba.fasta -lib tcoffee.lib mustang.lib
t_coffee tmalign_proba.fasta -lib tcoffee.lib tmalign.lib
t_coffee sap_mustang.fasta -lib sap.lib mustang.lib 
t_coffee mustang_tmalign.fasta -lib mustang.lib tmalign.lib
t_coffee tmalign_sap.fasta -lib tmalign.lib sap.lib

clustalw clustalw.fasta 
mafft mafft.fasta > mafft.temp
t_coffee -other_pg seq_reformat mafft.temp -output clustalw > mafft.aln
msaprobs msaprobs.fasta -o msaprobs.temp
t_coffee -other_pg seq_reformat msaprobs.temp -output clustalw > msaprobs.aln
muscle -in muscle.fasta -out muscle.temp
t_coffee -other_pg seq_reformat muscle.temp -output clustalw > muscle.aln
prank -d=prank.fasta -o=prank.temp
t_coffee -other_pg seq_reformat prank.temp.2.fas -output clustalw > prank.aln
probcons probcons.fasta > probcons.temp
t_coffee -other_pg seq_reformat probcons.temp -output clustalw > probcons.aln
export PYTHONPATH="/users/cn/jchang/local/Python/lib/python2.6/site-packages/"
python /users/cn/jchang/program/satesrc-v2.2.5-2012Oct16/sate-core/run_sate.py --input sate.fasta --datatype=Protein --num-cpus=1 --output-directory=tmp_sate --auto
t_coffee -other_pg seq_reformat ./tmp_sate/satejob*.marker001.sate.aln -output clustalw > sate.aln

# IRMSD-NIRMSD OF ALL MSAS
t_coffee -other_pg irmsd sap.aln -template_file modified.template > sap_irmsd
t_coffee -other_pg irmsd mustang.aln -template_file modified.template > mustang_irmsd
t_coffee -other_pg irmsd tmalign.aln -template_file modified.template > tmalign_irmsd
t_coffee -other_pg irmsd tcoffee.aln -template_file modified.template > tcoffee_irmsd
t_coffee -other_pg irmsd mcoffee.aln -template_file modified.template > mcoffee_irmsd
t_coffee -other_pg irmsd 3Dmcoffee.aln -template_file modified.template > 3Dmcoffee_irmsd
t_coffee -other_pg irmsd sap_proba.aln -template_file modified.template > sap_proba_irmsd
t_coffee -other_pg irmsd mustang_proba.aln -template_file modified.template > mustang_proba_irmsd
t_coffee -other_pg irmsd tmalign_proba.aln -template_file modified.template > tmalign_proba_irmsd
t_coffee -other_pg irmsd sap_mustang.aln -template_file modified.template > sap_mustang_irmsd
t_coffee -other_pg irmsd mustang_tmalign.aln -template_file modified.template > mustang_tmalign_irmsd
t_coffee -other_pg irmsd tmalign_sap.aln -template_file modified.template > tmalign_sap_irmsd
t_coffee -other_pg irmsd clustalw.aln -template_file modified.template > clustalw_irmsd
t_coffee -other_pg irmsd mafft.aln -template_file modified.template > mafft_irmsd
t_coffee -other_pg irmsd msaprobs.aln -template_file modified.template > msaprobs_irmsd
t_coffee -other_pg irmsd muscle.aln -template_file modified.template > muscle_irmsd
t_coffee -other_pg irmsd prank.aln -template_file modified.template > prank_irmsd
t_coffee -other_pg irmsd probcons.aln -template_file modified.template > probcons_irmsd
t_coffee -other_pg irmsd sate.aln -template_file modified.template > sate_irmsd

# Compute average ID% at each step: pfam, redundancy, pdb blast and filter steps.
t_coffee -other_pg seq_reformat PF*.fasta -output sim_idscore > 01_pfam_id
t_coffee -other_pg seq_reformat data_99.fasta -output sim_idscore > 02_redundancy_id
t_coffee -other_pg seq_reformat temp.fasta -output sim_idscore > 03_pdb_id
t_coffee -other_pg seq_reformat modified.fasta -output sim_idscore > 04_filt_id

# Compute average ID% for each alignment
t_coffee -other_pg seq_reformat sap.aln -output sim > sap_id
t_coffee -other_pg seq_reformat mustang.aln -output sim > mustang_id
t_coffee -other_pg seq_reformat tmalign.aln -output sim > tmalign_id
t_coffee -other_pg seq_reformat tcoffee.aln -output sim > tcoffee_id
t_coffee -other_pg seq_reformat mcoffee.aln -output sim > mcoffee_id
t_coffee -other_pg seq_reformat 3Dmcoffee.aln -output sim > 3Dmcoffee_id
t_coffee -other_pg seq_reformat sap_proba.aln -output sim > sap_proba_id
t_coffee -other_pg seq_reformat mustang_proba.aln -output sim > mustang_proba_id
t_coffee -other_pg seq_reformat tmalign_proba.aln -output sim > tmalign_proba_id
t_coffee -other_pg seq_reformat sap_mustang.aln -output sim > sap_mustang_id
t_coffee -other_pg seq_reformat mustang_tmalign.aln -output sim > mustang_tmalign_id
t_coffee -other_pg seq_reformat tmalign_sap.aln -output sim > tmalign_sap_id
t_coffee -other_pg seq_reformat clustalw.aln -output sim > clustalw_id
t_coffee -other_pg seq_reformat mafft.aln -output sim > mafft_id
t_coffee -other_pg seq_reformat msaprobs.aln -output sim > msaprobs_id
t_coffee -other_pg seq_reformat muscle.aln -output sim > muscle_id
t_coffee -other_pg seq_reformat prank.aln -output sim > prank_id
t_coffee -other_pg seq_reformat probcons.aln -output sim > probcons_id
t_coffee -other_pg seq_reformat sate.aln -output sim > sate_id

# PSI-COFFEE single core
t_coffee psicoffee.fasta -mode psicoffee -blast=LOCAL -protein_db=/db/ncbi/201304/blast/db/nr.fa -out_lib psicoffee.lib -multi_core=no

t_coffee -other_pg irmsd psicoffee.aln -template_file modified.template > psicoffee_irmsd
rm all_irmsd

t_coffee -other_pg seq_reformat psicoffee.aln -output sim > psicoffee_id


# clean the folder by moving all temporary and parameter files in OUTPUT folder
mv *.prf *.html *.dnd *.struc_tree.consense_output *.struc_tree.list super.pml *.fas tmp_sate *.temp *.lib run_aln.*  OUTPUT
